sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ys/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ys/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-535688970980'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
