sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ys/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ys/docker-react npm run test -- --coverage

  
